apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: exdmgifzj-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:b156f3f93752cd94f15c6547315b33dabfc8568b@sha256:8246c9e4aa0727c7224b4aa3b20905038aebf42f5ee5e15c9e76ad7f3f4654a8
        name: container-image  
